---
# Загружаем последнюю актуальную версию node_exporter
- name: get node_exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter-linux-amd64.tar.gz

# Распаковываем содержимое архива
- name: extract node_exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: "--strip-components=1"

# Копируем файл службы node_exporter
- name: create node_exporter service
  ansible.builtin.template:
    src: templates/node_exporter.service.j2
    dest: /lib/systemd/system/node_exporter.service

# Включаем службу node_exporter
- name: enable node_exporter service
  ansible.builtin.file:
    src: /lib/systemd/system/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    state: link

# Запускаем службу node_exporter
- name: start node_exporter service
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter
